print("-------------------------------------------------")
print("_________Quien Quiere ser millonario_____________")
print("¿Estas listo...")
print(".")
input("¿Si o no?")
print("No importa si estas listo o no, igual vas a jugar")
print("")
print("------------------------1era-Pregunta------------------------")
print("")